services:
  - docker
before_install:
  - docker pull polyverse/rust-dev-env
script:
  - docker run -v cargo-cache:/root/.cargo/registry -v $PWD:/volume --rm -t polyverse/rust-dev-env cargo clippy --all-targets
  - docker run -v cargo-cache:/root/.cargo/registry -v $PWD:/volume --rm -t polyverse/rust-dev-env cargo clippy --all-targets --features="async"

  # Test with cartesian product of features: async on/off and ptr on/off
  - docker run -v cargo-cache:/root/.cargo/registry -v $PWD:/volume --rm -t polyverse/rust-dev-env cargo test --all-targets
  - docker run -v cargo-cache:/root/.cargo/registry -v $PWD:/volume --rm -t polyverse/rust-dev-env cargo test --all-targets --features="async"
